#!/bin/sh

# while bspc subscribe -c 1 node_focus node_flag > /dev/null; do
#     bspc config border_with $(bspc config border_width)"
#     bsp config -n "$(bspc query -N -n .marked)" border_width 10;;
#     bsp config -n "$(bspc query -N -n !.marked)" border_witdh 2;;
# done

: "${MARKED_NORMAL_BCOLOR:=0x0000ff}"
: "${MARKED_ACTIVE_BCOLOR:=0x00ff00}"
: "${MARKED_FOCUSED_BCOLOR:=0xff0000}"

while bspc subscribe -c 1 node_focus node_flag > /dev/null; do
    bspc config focused_border_color "$(bspc config focused_border_color)"

    bspc query -N -n '.marked.!focused.window' | while read -r wid; do
        chwb -c "$MARKED_NORMAL_BCOLOR" "$wid"
    done
    bspc query -N -n '.marked.active.!focused.window' | while read -r wid; do
        chwb -c "$MARKED_ACTIVE_BCOLOR" "$wid"
    done
    bspc query -N -n "focused.marked" | while read -r wid; do
        chwb -c "$MARKED_FOCUSED_BCOLOR" "$wid"
    done
done
