#!/bin/sh

# landscape (normal)

xrandr -o normal
xinput set-prop "ELAN Touchscreen" "Coordinate Transformation Matrix" 0 0 0 0 0 0 0 0 0
xinput set-prop "SynPS/2 Synaptics TouchPad" "Device Enabled" 1
# xinput set-prop "SynPS/2 Synaptics TouchPad" "Coordinate Transformation Matrix" 0 0 0 0 0 0 0 0 0
