#!/bin/sh

# portrait (left)

xrandr -o left
xinput set-prop "ELAN Touchscreen" "Coordinate Transformation Matrix" 0 -1 1 1 0 0 0 0 1
xinput set-prop "SynPS/2 Synaptics TouchPad" "Device Enabled" 0
# xinput set-prop "SynPS/2 Synaptics TouchPad" "Coordinate Transformation Matrix" 0 -1 1 1 0 0 0 0 1
